### PR TITLE
Set locale to C before parsing XML files

### PR DESCRIPTION
**Pull request by MarkusFrankATcernch**
BEGINRELEASENOTES
Before starting to parse XML files, programatically set the locale to "C" if any of the three
- LC_NUMERIC,
- LC_TIME,
- LC_CTYPE
Is not set to "C".

Addresses issue https://github.com/AIDASoft/DD4hep/issues/913.
ENDRELEASENOTES

### CODE REVIEW

**Comment by veprbl** [comment]
Since DD4hep is a library, it would be nice to also restore the locale after you are done with it.

**Comment by MarkusFrankATcernch** [comment]
@veprbl You have a point here. I have think how to do this in some elegant way.

**Comment by veprbl** [comment]
I was fixing a similar issue for YODA. Here is how it went:
https://gitlab.com/hepcedar/yoda/-/commit/33437490c9101e8f6fa4aaa12e032ee91e95e32f

**Comment by MarkusFrankATcernch** [comment]
@veprbl I think this approach does not work. I can only switch between full locales outside of streams. All internal stuff is then happening e.g. in XercesC etc....I reverted.

**Comment by veprbl** [comment]
There is also a routine to change and restore the locales, it seems to be portable enough to at least compile with gcc and for macOS.

**Comment by MarkusFrankATcernch** [comment]
@veprbl Naaaa....look, this is what happens. Normally a class like this could guard all major XML parsing blocks:
```
    std::locale locale_current  {""};  // OS locale, NOT program locale
    std::locale locale_C {"C"};  // C locale
    TemporaryLocale()   {                        <<< Locale is program locale
      std::locale::global(locale_C);           <<< Locale becomes C
    }
    ~TemporaryLocale()   {
      std::locale::global(this->locale_current);   <<<< Locale becomes OS locale
    }                                                                   <<<< locale is no longer the same as before the constructor.
```
There is no call to get the current program locale. Hence, there is no simple way to construct such a guard.

**Comment by veprbl** [comment]
I don't remember all the details, but I vaguely remember that, indeed, you can't do a lot with locales from the C++ standard library. But looking at my commit, it seems like the `uselocale` function return a handler for a previous locale.

**Pull request merged**
