### PR TITLE
Add badge and link to online coverity service

### PR DESCRIPTION
**Pull request by andresailer**
1) can everyone see the coverity issues?

2) coverity check is run by hand on local machine and output uploaded to their server where the scan is run. Will do this once in a while.

### CODE REVIEW

**Comment by petricm** [comment]
I think you need to be added to the project before you can see this.

**Comment by andresailer** [comment]
I think you just need to be logged in to the coverity service with your github account

**Comment by petricm** [comment]
No. Was logged in and still there was this "Do you want to see the defects?" -> "Add me to the project". The red button on the right "View defects" was not there.

**Comment by andresailer** [comment]
OK, invited  @MarkusFrankATcernch and @gaede to the coverity thing

**Pull request merged**
