### PR TITLE
Adding segmentations from FCCSW

### PR DESCRIPTION
**Pull request by jlingema**
In case these are useful for someone else :-)

BEGINRELEASENOTES

- Adding GridRPhiEta a segmentation of equidistant size in R, Phi and Pseudorapidity
- Adding GridPhiEta a segmentation of equidistant size in Phi and Pseudorapidity

ENDRELEASENOTES

### CODE REVIEW

**Comment by petricm** [comment]
Can you also add the plugin functionality e.g. https://github.com/AIDASoft/DD4hep/pull/97

**Comment by jlingema** [comment]
Hi Marko - I added the plugins but wasn't sure about [this guy](https://github.com/AIDASoft/DD4hep/pull/97/commits/faaee1402a07ae81f64dc8d0fdbadd42a6d86fab#diff-fc95866ce67cb6cb4e3580cf33749c5dR39). Do you want it also added in py?

**Comment by petricm** [comment]
Yes add it also there please

**Comment by andresailer** [comment]
Breaks builds on mac: 
* https://gitlab.cern.ch/CLICdp/DD4hep/builds/286324
* https://gitlab.cern.ch/CLICdp/DD4hep/builds/286325

**Comment by jlingema** [comment]
Missing the new TVector dependency in DDSegmentation. A bit bizarre that it works on other platforms.

Looking at the [CMakeLists.txt](https://github.com/AIDASoft/DD4hep/blob/master/DDSegmentation/CMakeLists.txt) in DDSegmentation, it is very different from the others (it is not using `dd4hep_package`). When anyway having to change it, should it be re-written to be in line with the others?

**Comment by andresailer** [comment]
DDSegmentation used to be a standalone package, I thought @MarkusFrankATcernch already changed it to be no longer stand alone

**Pull request merged**
