### PR TITLE
Upgrade MiniTel example to serve as example for issue

### PR DESCRIPTION
**Pull request by MarkusFrankATcernch**
BEGINRELEASENOTES
- MiniTel Generate example should replect the detector in issue (https://github.com/AIDASoft/DD4hep/issues/1091)

ENDRELEASENOTES

### CODE REVIEW

**Comment by MarkusFrankATcernch** [comment]
@andresailer In test job https://github.com/AIDASoft/DD4hep/actions/runs/4797217643/jobs/8535995123
There seems to be a mismatch in the Geant4 version. Is this true?

**Comment by andresailer** [comment]
@MarkusFrankATcernch I think the problem is rather missing geant4 include dirs in ROOT_INCLUDE_PATH
I wanted to debug this soon. And the DDCad problem is hopefully solved with https://github.com/AIDASoft/DD4hep/pull/1099

**Comment by andresailer** [comment]
Actually the Geant4 include path given to the command in the test is wrong, there is a superfluous lib64 
`-I/cvmfs/sw.hsf.org/spackages7/geant4/11.1.1/x86_64-centos7-gcc11.2.0-opt/jlctn/lib64/include/Geant4`,

**Comment by andresailer** [comment]
The location of the Geant4Config.cmake etc. changed in 11.1.1? now it is in `lib64/cmake/Geant4`, instead of `lib64/Geant4-11.1.0`, and we derive the wrong location of the include directories from that.

**Pull request merged**
