### PR TITLE
Fix as reported from CMS

### PR DESCRIPTION
**Pull request by MarkusFrankATcernch**
BEGINRELEASENOTES
- Fix as reported from CMS
ENDRELEASENOTES

### CODE REVIEW

**Comment by MarkusFrankATcernch** [comment]
@ianna 
Once this is merged, this shall be your fix

**Comment by MarkusFrankATcernch** [comment]
@ianna Checks fail. It will probably take a bit more of time.

**Comment by MarkusFrankATcernch** [comment]
@andresailer 
Hi Andre,
these checks all fail in ddsim. Does the log output tell you something?

Markus

**Comment by andresailer** [comment]
I guess there is something even worse now with the Assembly cleanup?
```
 *** Error in `python': free(): invalid pointer: 0x000000000de24878 ***
======= Backtrace: =========
/lib64/libc.so.6(+0x81329)[0x7f210f83e329]
/cvmfs/sft.cern.ch/lcg/views/LCG_97a/x86_64-centos7-gcc8-opt/lib64/libG4geometry.so(_ZN15G4AssemblyStore5CleanEv+0x7f)[0x7f20ead193df]
/cvmfs/sft.cern.ch/lcg/views/LCG_97a/x86_64-centos7-gcc8-opt/lib64/libG4geometry.so(_ZN15G4AssemblyStoreD1Ev+0x17)[0x7f20ead194d7]
```

**Comment by andresailer** [comment]
Related issue in cmssw https://github.com/cms-sw/cmssw/issues/33608

**Comment by MarkusFrankATcernch** [comment]
This issue cannot be resolved easily. Needs re-discussion.

**Pull request closed without merging**
