### PR TITLE
Test DD4HEP_BUILD_DEBUG

### PR DESCRIPTION
**Pull request by andresailer**
Checking if the flag is correctly forwarded and the tests pass

### CODE REVIEW

**Comment by andresailer** [comment]
@MarkusFrankATcernch
this DDCore "dependency" works at least from the cmake point of view.

This test is failing however
```
 16/248 Test   #9: t_AlignDet_Telescope_readback_xml .............................***Failed  Required regular expression not found. Regex=[40 conditions in slice. \(T:21,S:21,L:0,C:0,M:0\) Alignments accessed: 20 \(A:19,M:0\) for IOV:run\(1\)
...
 Example          INFO  52 conditions in slice. (T:33,S:33,L:0,C:0,M:0) Alignments accessed: 20 (A:19,M:0) for IOV:run(1)      
geoPluginRun: [   0.026 sec] Executed dd4hep plugin: 'DD4hep_AlignmentExample_read_xml' with args (4) :[ -input file:/Package/examples/examples/AlignDet/compact/Telescope.xml -deltas file:./new_cond.xml ]
ConditionsPool   INFO  +++ Remove Conditions for pool with IOV: run(1):[1000-2000]               age:  0 [  52 entries]
```

**Comment by MarkusFrankATcernch** [comment]
Will you merge this request ?
Thanks!

**Comment by andresailer** [comment]
Yes, but why does the test fail?

**Comment by MarkusFrankATcernch** [comment]
I do not really know why these tests fail. I see this also on the command line. It looks more that the test bases itself on some leftovers from a previous test. It only happens on these two slots.

**Comment by andresailer** [comment]
It only happens on the slots where the DEBUG flag is enabled

**Comment by MarkusFrankATcernch** [comment]
Huuhh?? This is strange. Then I have to investigate a bit.

**Comment by andresailer** [comment]
Thanks!

**Pull request merged**
