### PR TITLE
bug fix in Geant4EventReaderGuineaPig

### PR DESCRIPTION
**Pull request by petricm**
BEGINRELEASENOTES
- bug fix in Geant4EventReaderGuineaPig
     - fix ignoring input lines with 'nan'

ENDRELEASENOTES

### CODE REVIEW

**Comment by gaede** [comment]
@petricm the release tag v01-07-02 needs to be made on the the branch rel_v01-07 !!!!

**Comment by gaede** [comment]
... its not a good idea, if we try to tag releases at the same time ...

**Comment by petricm** [comment]
sorry we were causing interference to each other. Please let me fix it.

**Comment by gaede** [comment]
Ok.

**Comment by petricm** [comment]
fixed.

**Pull request merged**
