### PR TITLE
Revert PR #193

### PR DESCRIPTION
**Pull request by andresailer**
Revert PR #193  as it breaks loading of plugins, or something
```
ddsim --compactFile=${lcgeo_DIR}/CLIC/compact/CLIC_o2_v04/CLIC_o2_v04.xml --runType=shell -G -N=100 --outputFile=testCLIC_o2_v04.slcio --gun.isotrop=true --steeringFile=../examples/clic_steer.py
[snip]
Detector         INFO  +++ Patching names of anonymous shapes....
InstallSurfaceManager INFO  **** running plugin InstallSurfaceManager !
DD4hepVolumeManager INFO  **** running plugin DD4hepVolumeManager !
VolumeManager    INFO   - populating volume ids - be patient ...
VolumeManager    INFO   - populating volume ids - done
VolumeManager    INFO  +++ Volume manager populated and loaded.
Traceback (most recent call last):
   File "/data/sailer/software/ILCSOFT/HEAD-2016-12-05/lcgeo/HEAD/bin/ddsim", line 16, in <module>
     RUNNER.run()
   File "/data/sailer/software/ILCSOFT/HEAD-2016-12-05/lcgeo/HEAD/lib/python/DDSim/DD4hepSimulation.py", line 275, in run
     kernel.loadGeometry("file:"+ self.compactFile )
Exception: void dd4hep::sim::Geant4Kernel::loadGeometry(const string& compact_file) =>
     *** findVolume: Invalid  placement:  - node pointer Null !
dd4hep: with plugin:InstallSurfaceManager
dd4hep: Error interpreting XML nodes of type <plugin/>
dd4hep: Error interpreting XML nodes of type <plugins/>
dd4hep: while parsing file:/data/sailer/software/ILCSOFT/HEAD-2016-12-05/lcgeo/HEAD/CLIC/compact/CLIC_o2_v04/CLIC_o2_v04.xml
dd4hep: with plugin:DD4hepXMLLoader (C++ exception of type runtime_error)
```

### CODE REVIEW

**Comment by gaede** [comment]
@andresailer I have a fix for the problem - PR will come soon ...

**Comment by andresailer** [comment]
Ok, even better

**Comment by MarkusFrankATcernch** [comment]
Yes. It would be very good if it would work again.
There is also another generic problem: The linking of our libraries sucks.
It somehow does not require that all referenced functions are actually resolved. This is very bad.

**Comment by petricm** [comment]
I think that the issue "not require that all referenced functions are actually resolved" we were already discussing on a meeting, and decided not to change this behavior at that moment, but we all agreed that this should be changed at some point.

**Pull request closed without merging**
