### PR TITLE
Fix Issue 875

### PR DESCRIPTION
**Pull request by MarkusFrankATcernch**
BEGINRELEASENOTES
- Recursive calls to apply-plugins overwrote the return code.
- This MR fixes issue https://github.com/AIDASoft/DD4hep/issues/875

- Support for 1D, 2D and 3D parameterised volumes.
  (Outstanding request by S.Ko)
  1. TGeo does not support parametrized volumes intrinsically.
    On the dd4hep/TGeo side these are implemented by multiple placements 
    according to the user supplied transformation matrices.
    For details see the calls in `dd4hep::Volume::paramVolume<dim>D(...)`
  2. When translated to Geant4, the structures are identified and
    the proper Geant4 parameterisation is created.
  3. An example can be found in:
    - `examples/ClientTests/src/ParamVolume_geo.cpp`
    - to display: `geoDisplay examples/ClientTests/compact/ParamVolume<dim>D.xml`
    - the Geant4 conversion is excercised with the scripts:
      ```
      python examples/ClientTests/scripts/ParamVolume.py \
         -geometry examples/ClientTests/compact/ParamVolume<dim>D.xml \
         -vis -macro examples/ClientTests/compact/ParamVolume.mac ```
ENDRELEASENOTES

### CODE REVIEW

**Comment by MarkusFrankATcernch** [comment]
@SanghyunKo This MR might be of interest to you.

**Comment by SanghyunKo** [comment]
Thanks @MarkusFrankATcernch, this is neat. I used to work around it by using horrendous multiple loops...

**Comment by vvolkl** [comment]
Hi @MarkusFrankATcernch, we see the following runtime error in the lcgeo tests in our nightlies, do you think it could be related to this PR?
```
 8099 ----------------------------------------------------------------
 8100 
 8101 Traceback (most recent call last):
 8102   File "/cvmfs/sw-nightlies.hsf.org/spackages5/dd4hep/commit.02c6d5ac04c187f37631f9f15ca6c1c08452d992/x86_64-centos7-gcc11.2.0-opt/yvder/bin/ddsim", line 25, in <modul      e>
 8103     RUNNER.run()
 8104   File "/cvmfs/sw-nightlies.hsf.org/spackages5/dd4hep/commit.02c6d5ac04c187f37631f9f15ca6c1c08452d992/x86_64-centos7-gcc11.2.0-opt/yvder/lib/python3.9/site-packages/DD      Sim/DD4hepSimulation.py", line 306, in run
 8105     kernel.loadGeometry(str("file:" + compactFile))
 8106 cppyy.gbl.std.runtime_error: void dd4hep::sim::Geant4Kernel::loadGeometry(const string& compact_file) =>
 8107     runtime_error: dd4hep: apply-plugin: Failed to execute plugin lcgeo_LinearSortingPolicy
 8108 dd4hep: with plugin:lcgeo_LinearSortingPolicy
 8109 dd4hep: Error interpreting XML nodes of type <plugin/>
 8110 dd4hep: Error interpreting XML nodes of type <plugins/>
 8111 dd4hep: while parsing file:/tmp/gitlab-runner/spack-stage/spack-stage-lcgeo-commit.2220bc8428381dab91b1934a235bbf177522320c-5wahn7aynqewkli5cd6znujgkkmu7vhx/spack-src/      lcgeoTests/../FCCee/compact/FCCee_o1_v04/FCCee_o1_v04.xml
 8112 dd4hep: with plugin:DD4hep_XMLLoader
 8113 <end of output>
 8114 Test time = 139.46 sec
 8115 ----------------------------------------------------------
 8116 Test Fail Reason:
 8117 Error regular expression found in output. Regex=[Error]
 8118 "t_test_FCCee_o1_v04" end time: Jul 28 06:46 CEST
 8119 "t_test_FCCee_o1_v04" time elapsed: 00:02:19
```

**Comment by andresailer** [comment]
Hi @vvolkl , yes it is related. I need to change the return value of that plugin, I think.

**Pull request merged**
