### PR TITLE
Fix bug in Polyhedra shape

### PR DESCRIPTION
**Pull request by MarkusFrankATcernch**
BEGINRELEASENOTES
- Fix bug in Polyhedra shape.
  See issue https://github.com/AIDASoft/DD4hep/issues/544 for details .
- Update optical surface example to resolve issue https://github.com/AIDASoft/DD4hep/issues/440 .
ENDRELEASENOTES

### CODE REVIEW

**Comment by ianna** [comment]
@mrodozov and @smuzaffar - FYI

**Comment by MarkusFrankATcernch** [comment]
Dear Yana et al,
could you please check if this fixes the polyhedra problem?
Thanks!

**Comment by mrodozov** [comment]
is this anyhow related to https://github.com/root-project/root/pull/4006 ?

**Comment by MarkusFrankATcernch** [comment]
No, this is independent. This should only fix issue https://github.com/AIDASoft/DD4hep/issues/544.
https://github.com/root-project/root/pull/4160 is for ROOT v6.20 when we hopefully can move to Geant4 units.

**Comment by mrodozov** [comment]
ok then, they could go separated in.
Thanks

**Comment by ianna** [comment]
> Dear Yana et al,
> could you please check if this fixes the polyhedra problem?
> Thanks!

Hi Markus,


Thanks, it was fixed. See the snapshots before and after attached.

Thanks, 
Yana

Screen Shot 2019-08-09 at 16 46 37
Screen Shot 2019-08-09 at 16 41 42

**Pull request merged**
