### PR TITLE
Support all CMake booleans

### PR DESCRIPTION
**Pull request by HadrienG2**
CMake supports other Boolean truth values than "ON" and "OFF", including for example "TRUE"/"FALSE", "0"/"1", and "YES"/"NO". Therefore, hardcoding boolean comparisons to "ON"/"OFF" will cause subtle problems when CMake is used in an unintended way and is best avoided.

BEGINRELEASENOTES
 - Remove if string equals ON/OFF in cmake IF statements and check default CMake truth values

ENDRELEASENOTES

### CODE REVIEW

**Comment by petricm** [comment]
thank you for your contribution and I see your point, but this in it's current state breaks everything. Please fix the PR.

**Comment by HadrienG2** [comment]
You're right, I missed some use of undefined variables. Adding a check of defined-ness...

**Comment by HadrienG2** [comment]
Ok, this version looks good.

**Comment by petricm** [comment]
thank you for fixing it, please just squash the commits.

**Comment by HadrienG2** [comment]
Done!

**Comment by MarkusFrankATcernch** [comment]
Marko,
if you agree with this solution,please merge.

**Pull request merged**
