### PR TITLE
DDDetector: Fix overlaps

### LINKED ISSUE #257: DDDetectors: Volume overlaps
In the process of working with DD4hep and a SiD-based detector, I have noticed issues with volume overlaps/extrusions with a few detector types in DDDetectors.  I've used `TGeoManager` to check for overlaps.

At a minimum, the following constructors produce overlaps for me:
* `DD4hep_EcalBarrel`
* `DD4hep_CylindricalEndcapCalorimeter`
* `DD4hep_ForwardDetector`

I have already taken the time to fix the first one, and I will soon get to the others.  The `DD4hep_EcalBarrel` overlaps are quite significant, and I think that if any work has relied on it, that work should be reexamined to see if the overlaps have caused an issue.

I've also noted that once `DD4hep_EcalBarrel` is fixed, the behavior seems to be the same as `DD4hep_PolyhedraBarrelCalorimeter2`, so perhaps it is superfluous.

### PR DESCRIPTION
**Pull request by decibelcooper**
This PR resolves #257 

BEGINRELEASENOTES
- Corrected `EcalBarrel` constructor after finding significant layer overlaps
- Corrected `CylindricalEndcapCalorimeter` factors of 2 in layer/slice thickness
- Corrected `ForwardDetector` factors of 2 in layer/slice thickness

ENDRELEASENOTES

### CODE REVIEW

**Comment by decibelcooper** [comment]
I have verified these changes by converting to GDML and performing overlap check and visual inspection with TGeoManager.

**Comment by andresailer** [comment]
Which detector model (XML files) did you use for the checks?
Also in the past we found that the geant4 overlap checker is more sensitive and reliable than the TGeo overlap checker, so maybe you could also run the geometry checker in geant4 (/geometry/test/run I think).

**Comment by decibelcooper** [comment]
@andresailer The compact files can be found [here](https://eicweb.phy.anl.gov/EIC/NPDet/tree/master/src/ConceptDetectors/SiEIC/compact). It is a modified SiD description.

I am currently running a zero-tolerance check with `/geometry/test/run`.  It will take a bit of time.

**Comment by decibelcooper** [comment]
I have confirmed that `/geometry/test/run` finds overlaps before this PR with this above compact files, and there are no overlaps with this PR.

**Pull request merged**
