### PR TITLE
Shapes: Sphere fix conversion for startTheta

### PR DESCRIPTION
**Pull request by andresailer**
BEGINRELEASENOTES
- Shapes: fix conversion of `startTheta` for Sphere::setDimensions
- Shapes::get_shape_dimension: add return value conversion for angles to internal unit (radians)

ENDRELEASENOTES

### CODE REVIEW

**Comment by andresailer** [comment]
Shouldn't these angles (`GetTheta`, etc.) have `*units::deg` ?

https://github.com/AIDASoft/DD4hep/blob/9f9459d008972c8944ae8185b5ee4da16010b3e5/DDCore/src/Shapes.cpp#L117

**Comment by MarkusFrankATcernch** [comment]
I do not know exactly. 
This piece of code was triggered by CMS. I do not know exactly what they expect here to be returned.
Otherwise you are right -- and there are several other inconsistencies then.

**Comment by andresailer** [comment]
So maybe @ianna can tell us.
I would think that chains of `get_shape_dimensions` and `setDimensions` should work without manual unit transformations.

**Comment by ianna** [comment]
we assume that the returned angles are in **deg** and convert them to **rad** ourselves

**Comment by MarkusFrankATcernch** [comment]
@ianna : This approach looks very inconsistent. 
The dd4hep shape constructors take radians, but setDimension/getDimension use degrees. 
This does not sound logical to me.

**Comment by ianna** [comment]
@MarkusFrankATcernch - agree, if you switch setDimension/getDimension to rad for consistency, we adapt our code.

**Comment by andresailer** [comment]
Then I will add the unit conversion in the getDimensions (get_shape_dimensions) function.

**Comment by ianna** [comment]
@cvuosalo - FYI, we'll need to keep an eye on it and remove the deg to rad conversion from the code when this is merged to the master and the dd4hep external is updated.

**Comment by andresailer** [comment]
Added the conversion, someone please double check

**Pull request merged**
