### PR TITLE
feat: Geant4OpticalTrackerAction which stops-and-kills optical photons

### PR DESCRIPTION
**Pull request by wdconinc**
In the EIC detectors we use various photo-sensitive pixel planes in the DIRC and RICH detectors. This is similar to a tracker in the overall SD action sense, but instead of requiring optical photons energy deposition in the material of the sensor (e.g. SiPM, LAPPD, AC-LGAD), we often don't model the optical properties of the materials in the sensors and simply stop-and-kill the optical photon when it reaches the sensor. This is an SD action that achieves this.

I have no geometry to easily test the `processFastSim` functionality with.

BEGINRELEASENOTES
- Geant4OpticalTrackerAction which stops-and-kills optical photons for e.g. SiPM sensor planes

ENDRELEASENOTES

### CODE REVIEW

**Comment by andresailer** [comment]
Hi Wouter,
Do you have a simple detector that we could add to the examples to use this plugin?

**Comment by wdconinc** [comment]
> simple detector

Well... Probably not an entire RICH? Though maybe @c-dilks would be open to turning our dual RICH into a standalone example that demonstrates this. Otherwise we can also do our proximity-focused RICH which is a bit simpler.

**Comment by c-dilks** [comment]
Hi @wdconinc, I opened https://github.com/wdconinc/DD4hep/pull/2 targeting your fork's branch, which adds a PFRICH. It needs some more work to make it nice, but I think I see the increase in the number of hits. See the description within for more details.

**Comment by wdconinc** [comment]
> Do you have a simple detector that we could add to the examples to use this plugin?

Example added as #974. Not sure if it's what you'd consider 'simple' but it is at least much simpler than how we are using it in production :-D

So, I'd suggest either merging this and moving example discussion to the example PR, or closing this and merging the tracker SD action as part of the example PR.

**Comment by andresailer** [comment]
Thanks! I will merge this, and then #974 can be rebased to add the example.

**Pull request merged**
