### PR TITLE
multiple vertices per interaction continued

### PR DESCRIPTION
**Pull request by gaede**
- change Geant4PrimaryInteraction::VertexMap to
  std::map<int,std::vector<Vertex*>>

### CODE REVIEW

**Comment by andresailer** [comment]
Did you check that this will produce the exact same result with existing stdhep files?

**Comment by gaede** [comment]
@andresailer: Of course I ran some tests with existing stdhep files.

@MarkusFrankATcernch can you have a quick look, if you are happy with these changes ?
It was a bit confusing that sometimes the mask is used as key in `Geant4PrimaryInteraction::VertexMap` and sometimes simply a counter w.r.t inserted vertices.

**Comment by MarkusFrankATcernch** [comment]
Looks OK. If the intended functionality is preserved can only be done with tests.

At the end what matters is: 
In the event of multiple inputs identified each identified by its mask, 
it must be possible to uniquely associate also the outputs (hits) to the corresponding
primary interactions. This was the intention for the masks and must be preserved.

**Comment by gaede** [comment]
Ok, I will merge this then. We need to of course run tests...

**Pull request merged**
