### PR TITLE
Fix facetIsDegenerated utility function

### PR DESCRIPTION
**Pull request by MarkusFrankATcernch**
BEGINRELEASENOTES
- Fix to MR https://github.com/AIDASoft/DD4hep/pull/1212
ENDRELEASENOTES

### CODE REVIEW

**Comment by andresailer** [comment]
Probably the epsilon too small, as you pointed out yesterday.
`      constexpr double epsilon = 1.e-20;`

**Comment by andresailer** [comment]
But it is failing tests related to ddcad...

**Comment by MarkusFrankATcernch** [comment]
@andresailer Hell, screwed it again!
Could you unroll please? This is getting too complicated in git for me.
The only important thing is the std::fabs(...) in the return.

**Comment by MarkusFrankATcernch** [comment]
@andresailer I do not get here any output on the failing slots:
https://github.com/AIDASoft/DD4hep/actions/runs/7544726687/job/20538715080

**Pull request merged**
