### PR TITLE
Re-enable commented out code

### PR DESCRIPTION
**Pull request by MarkusFrankATcernch**
BEGINRELEASENOTES
 * Re-enable commented out code in `segmentations/Segmentation.cpp`

ENDRELEASENOTES

### CODE REVIEW

**Comment by gaede** [comment]
... and what does this re-enabled code do ?

**Comment by andresailer** [comment]
Delete the parameters for segmentation and fix memory leaks

**Comment by gaede** [comment]
.. then this should maybe added to the release notes - I could see that from the code diff myself ;-)

**Comment by andresailer** [comment]
Actually as this is just a correction to the previous PR that will end up the same release there shouldn't be any release notes

**Comment by MarkusFrankATcernch** [comment]
This was a temporary leftover from the persistency exercise. I had problems with segmentations and had to find a work-around. 
BTW a major source of problems were also the BitField64 structures. These also need some re-thinking, since in addition they are a prime example of anti-multi-threaded code.

**Comment by gaede** [comment]
This is what get's added to the Release notes by the tagger script:
```
* 2017-07-14 Markus Frank ([PR#205](https://github.com/AIDASoft/DD4hep/pull/205))
  * Re-enable commented out code in `segmentations/Segmentation.cpp`
```

no big issue, but in general one should try and write reasonable PR comments ...

@MarkusFrankATcernch can you be a bit more specific about the BitField64 problem - or even better, create an issue ...

**Comment by petricm** [comment]
@gaede until you do a tag you can edit PR message and the BEGINRELEASENOTES tag and it will be picked up by the tagger script, regardless if it is already merged.

**Comment by gaede** [comment]
I know that Marko - and thought everyone else did as well - this is why I had written the first comment...

**Comment by MarkusFrankATcernch** [comment]
Folks, I am not against discussions, but this is getting absurd.
Do you really have so much energy left to waste it for such an non-issue?

**Pull request merged**
