### PR TITLE
Import ddsim

### PR DESCRIPTION
**Pull request by andresailer**
BEGINRELEASENOTES
- DDG4: Import the ddsim python program from https://github.com/iLCSoft/lcgeo
  For example:
   - `ddsim --help`
   - `ddsim --dumpSteeringFile > mySteer.py`
   - `ddsim --steeringFile=mySteer.py --compactFile myDetector.xml`

ENDRELEASENOTES

### CODE REVIEW

**Comment by andresailer** [comment]
Added the test which simulates the SiD detector https://travis-ci.org/AIDASoft/DD4hep/jobs/407032010#L1552

**Comment by peterkostka** [comment]
New **test_ddsim** expects libraries 
in $DD4hepINSTALL not in $DD4hepINSTALL/lib
Has to be changed.

**Comment by andresailer** [comment]
You have to be a lot more precise about the problem and its circumstances.

**Comment by peterkostka** [comment]
Compile and install on  MacOS - 10.13.6, 
using:
GEANT4 - 4.10.04.p02, 
ROOT - 6.14.00, 
boost - 1.67.0, 
xerces - 3.2.0,
lcio - 02-10-01,
gear - 01-06-01,
clhep - 2.4.0.1

**Compile and install - no problem**;

Excerpt from     Testing/Temporary/LastTest.log:
::::::::
12/12 Test: test_ddsim
Command: "/opt/DD4hep/install/bin/run_test.sh" "ddsim" "--compactFile=/opt/DD4hep/install/DDDetectors/compact/SiD.xml" "--runType=batch" "-G" "-N=2" "--outputFile=testSid.root" "--part.userParticleHandler="
Directory: /opt/DD4hep/build/DDTest
"test_ddsim" start time: Aug 01 08:52 CEST
Output:
----------------------------------------------------------
---running test :  ' ddsim --compactFile=/opt/DD4hep/install/DDDetectors/compact/SiD.xml --runType=batch -G -N=2 --outputFile=testSid.root --part.userParticleHandler= '
cling::DynamicLibraryManager::loadLibrary(): dlopen(/opt/aidasoft/DD4hep/install/lib/libDDCore.1.8.dylib, 9): Library not loaded: /opt/DD4hep/install/libDDParsers.1.8.dylib
  Referenced from: /opt/aidasoft/DD4hep/install/lib/libDDCore.1.8.dylib
  Reason: image not found
INFO: +--------------------------------------------------------------------------------------------------------+
INFO: |  Failed to load dd4hep base library:                                                                   |
INFO: |  dd4hep.py: Failed to load the dd4hep library libDDCore: No such file or directory                     |
INFO: +--------------------------------------------------------------------------------------------------------+

===================================
Fast fix in $DD4hepINSTALL - set symbolic links:
===================================
libDD4hepGaudiPluginMgr.1.8.dylib -> lib/libDD4hepGaudiPluginMgr.1.8.dylib*
libDDCore.1.8.dylib -> lib/libDDCore.1.8.dylib*
libDDG4.1.8.dylib -> lib/libDDG4.1.8.dylib*
libDDParsers.1.8.dylib -> lib/libDDParsers.1.8.dylib*
libDDRec.1.8.dylib -> lib/libDDRec.1.8.dylib*

**Comment by andresailer** [comment]
Doesn't happen on our mac tests, https://gitlab.cern.ch/CLICdp/DetectorSoftware/DD4hep/-/jobs/1852148
Do you source thisdd4hep.sh before running the tests?

**Comment by peterkostka** [comment]
yes, I do

**Comment by peterkostka** [comment]
**> cmake --version**
cmake version 3.11.0

**CMAKE - command:**

cmake \
-D CMAKE_INSTALL_NAME_DIR:STRING=$DD4hep/install \
-D CMAKE_INSTALL_PREFIX:STRING=$DD4hep/install \
-D CMAKE_CXX_FLAGS="-std=c++11" \
-D CMAKE_MACOSX_RPATH:BOOL=OFF \
-D CMAKE_MODULE_PATH:STRING=$DD4hep/cmake:$SWDIR/clhep/install/cmake \
-D CMAKE_C_COMPILER:STRING=clang \
-D CMAKE_CXX_COMPILER:STRING=clang++ \
-D DD4HEP_USE_BOOST:BOOL=ON \
-D BOOST_ROOT:STRING=$SWDIR/boost \
-D Boost_DIR:PATH=$SWDIR/boost \
-D Boost_INCLUDE_DIR=$SWDIR/boost/include \
-D BOOST_LIBRARYDIR:PATH=$SWDIR/boost/lib \
-D DD4HEP_USE_XERCESC:BOOL=ON \
-D XERCESC_ROOT_DIR:STRING=$SWDIR/xerces/install \
-D XERCESC_LIBRARY:FILEPATH=$SWDIR/xerces/install/lib/libxerces-c.dylib \
-D DD4HEP_USE_LCIO:BOOL=ON \
-D LCIO_DIR:STRING=$SWDIR/lcio/install \
-D DD4HEP_USE_GEAR:BOOL=ON \
-D GEAR_DIR=$GEAR_DIR  \
-D GEAR_GEARSURF_LIBRARY=$GEAR_DIR/lib/libgearsurf.dylib \
-D GEAR_GEAR_LIBRARY=$GEAR_DIR/lib/libgear.dylib \
-D GEAR_GEARXML_LIBRARY=$GEAR_DIR/lib/libgearxml.dylib \
-D GEAR_GEARTGEO_LIBRARY=$GEAR_DIR/lib/libgeartgeo.dylib \
-D DD4HEP_USE_ROOT:STRING=$SWDIR/root/root-install \
-D ROOT_DIR:STRING=$ROOTSYS \
-D ROOT_INCLUDE_DIR:STRING=$SWDIR/root/root-install/include/ \
-D ROOT_LIBRARY_DIR:STRING=$SWDIR/root/root-install/lib \
-D ROOT_Geom_LIBRARY:FILEPATH=$SWDIR/root/root-install/lib/libGeom.so \
-D DD4HEP_USE_GEANT4:BOOL=ON \
-D Geant4_DIR:STRING=$SWDIR/geant4/geant4-install \
-D CLHEP_ROOT_DIR:STRING=$SWDIR/clhep/install\
-D CLHEP_LIBRARY:STRING=$SWDIR/clhep/install/lib/libCLHEP-2.4.0.1.dylib \
-D CLHEP_INCLUDE_DIR:STRING=$SWDIR/clhep/install/include \
-D CMAKE_BUILD_TYPE=Debug \
-D BUILD_TESTING:BOOL=ON \
../

DD4HEP_LIBRARY_PATH=/opt/DD4hep/install/lib:/opt/xerces/install/lib:/opt/geant4/geant4-install/lib64:/opt/root/root-install/lib:/opt/QT/5.9.2/lib:/opt/boost/lib:

**> otool -L libDDCore.1.8.dylib**

libDDCore.1.8.dylib:
    /opt/DD4hep/install/libDDCore.1.8.dylib (compatibility version 1.8.0, current version 1.8.0)
    @rpath/libCore.so (compatibility version 0.0.0, current version 0.0.0)
    @rpath/libImt.so (compatibility version 0.0.0, current version 0.0.0)
    @rpath/libRIO.so (compatibility version 0.0.0, current version 0.0.0)
    @rpath/libNet.so (compatibility version 0.0.0, current version 0.0.0)
    @rpath/libHist.so (compatibility version 0.0.0, current version 0.0.0)
    @rpath/libGraf.so (compatibility version 0.0.0, current version 0.0.0)
    @rpath/libGraf3d.so (compatibility version 0.0.0, current version 0.0.0)
    @rpath/libGpad.so (compatibility version 0.0.0, current version 0.0.0)
    @rpath/libTree.so (compatibility version 0.0.0, current version 0.0.0)
    @rpath/libTreePlayer.so (compatibility version 0.0.0, current version 0.0.0)
    @rpath/libRint.so (compatibility version 0.0.0, current version 0.0.0)
    @rpath/libPostscript.so (compatibility version 0.0.0, current version 0.0.0)
    @rpath/libMatrix.so (compatibility version 0.0.0, current version 0.0.0)
    @rpath/libPhysics.so (compatibility version 0.0.0, current version 0.0.0)
    @rpath/libMathCore.so (compatibility version 0.0.0, current version 0.0.0)
    @rpath/libThread.so (compatibility version 0.0.0, current version 0.0.0)
    @rpath/libMultiProc.so (compatibility version 0.0.0, current version 0.0.0)
    @rpath/libGeom.so (compatibility version 0.0.0, current version 0.0.0)
    @rpath/libGenVector.so (compatibility version 0.0.0, current version 0.0.0)
    /opt/xerces/install/lib/libxerces-c-3.2.dylib (compatibility version 0.0.0, current version 0.0.0)
    /opt/DD4hep/install/libDDParsers.1.8.dylib (compatibility version 1.8.0, current version 1.8.0)
    /opt/DD4hep/install/libDD4hepGaudiPluginMgr.1.8.dylib (compatibility version 1.8.0, current version 1.8.0)
    /usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 400.9.0)
    /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1252.50.4)


**> otool -l libDDCore.1.8.dylib**

libDDCore.1.8.dylib:
Mach header
      magic cputype cpusubtype  caps    filetype ncmds sizeofcmds      flags
 0xfeedfacf 16777223          3  0x00           6    38       3120 0x00118085
Load command 0
      cmd LC_SEGMENT_64
  cmdsize 712
  segname __TEXT
   vmaddr 0x0000000000000000
   vmsize 0x000000000066c000
  fileoff 0
 filesize 6733824
  maxprot 0x00000007
 initprot 0x00000005
   nsects 8
    flags 0x0
Section
  sectname __text
   segname __TEXT
      addr 0x0000000000007680
      size 0x000000000055d040
    offset 30336
     align 2^4 (16)
    reloff 0
    nreloc 0
     flags 0x80000400
 reserved1 0
 reserved2 0
Section
  sectname __stubs
   segname __TEXT
      addr 0x00000000005646c0
      size 0x0000000000005dea
    offset 5654208
     align 2^1 (2)
    reloff 0
    nreloc 0
     flags 0x80000408
 reserved1 0 (index into indirect symbol table)
 reserved2 6 (size of stubs)
Section
  sectname __stub_helper
   segname __TEXT
      addr 0x000000000056a4ac
      size 0x0000000000001154
    offset 5678252
     align 2^2 (4)
    reloff 0
    nreloc 0
     flags 0x80000400
 reserved1 0
 reserved2 0
Section
  sectname __gcc_except_tab
   segname __TEXT
      addr 0x000000000056b600
      size 0x0000000000030338
    offset 5682688
     align 2^2 (4)
    reloff 0
    nreloc 0
     flags 0x00000000
 reserved1 0
 reserved2 0
Section
  sectname __const
   segname __TEXT
      addr 0x000000000059b940
      size 0x000000000001238b
    offset 5880128
     align 2^4 (16)
    reloff 0
    nreloc 0
     flags 0x00000000
 reserved1 0
 reserved2 0
Section
  sectname __cstring
   segname __TEXT
      addr 0x00000000005adccb
      size 0x00000000000b1142
    offset 5954763
     align 2^0 (1)
    reloff 0
    nreloc 0
     flags 0x00000002
 reserved1 0
 reserved2 0
Section
  sectname __unwind_info
   segname __TEXT
      addr 0x000000000065ee10
      size 0x000000000000b994
    offset 6680080
     align 2^2 (4)
    reloff 0
    nreloc 0
     flags 0x00000000
 reserved1 0
 reserved2 0
Section
  sectname __eh_frame
   segname __TEXT
      addr 0x000000000066a7a8
      size 0x0000000000001850
    offset 6727592
     align 2^3 (8)
    reloff 0
    nreloc 0
     flags 0x00000000
 reserved1 0
 reserved2 0
Load command 1
      cmd LC_SEGMENT_64
  cmdsize 712
  segname __DATA
   vmaddr 0x000000000066c000
   vmsize 0x0000000000034000
  fileoff 6733824
 filesize 106496
  maxprot 0x00000007
 initprot 0x00000003
   nsects 8
    flags 0x0
Section
  sectname __got
   segname __DATA
      addr 0x000000000066c000
      size 0x0000000000003748
    offset 6733824
     align 2^3 (8)
    reloff 0
    nreloc 0
     flags 0x00000006
 reserved1 4007 (index into indirect symbol table)
 reserved2 0
Section
  sectname __nl_symbol_ptr
   segname __DATA
      addr 0x000000000066f748
      size 0x0000000000000010
    offset 6747976
     align 2^3 (8)
    reloff 0
    nreloc 0
     flags 0x00000006
 reserved1 5776 (index into indirect symbol table)
 reserved2 0
Section
  sectname __la_symbol_ptr
   segname __DATA
      addr 0x000000000066f758
      size 0x0000000000007d38
    offset 6747992
     align 2^3 (8)
    reloff 0
    nreloc 0
     flags 0x00000007
 reserved1 5778 (index into indirect symbol table)
 reserved2 0
Section
  sectname __mod_init_func
   segname __DATA
      addr 0x0000000000677490
      size 0x0000000000000320
    offset 6780048
     align 2^3 (8)
    reloff 0
    nreloc 0
     flags 0x00000009
 reserved1 0
 reserved2 0
Section
  sectname __const
   segname __DATA
      addr 0x00000000006777b0
      size 0x0000000000003378
    offset 6780848
     align 2^4 (16)
    reloff 0
    nreloc 0
     flags 0x00000000
 reserved1 0
 reserved2 0
Section
  sectname __data
   segname __DATA
      addr 0x000000000067ab30
      size 0x000000000000aa80
    offset 6794032
     align 2^4 (16)
    reloff 0
    nreloc 0
     flags 0x00000000
 reserved1 0
 reserved2 0
Section
  sectname __bss
   segname __DATA
      addr 0x00000000006855b0
      size 0x0000000000016389
    offset 0
     align 2^4 (16)
    reloff 0
    nreloc 0
     flags 0x00000001
 reserved1 0
 reserved2 0
Section
  sectname __common
   segname __DATA
      addr 0x000000000069b940
      size 0x0000000000003e60
    offset 0
     align 2^3 (8)
    reloff 0
    nreloc 0
     flags 0x00000001
 reserved1 0
 reserved2 0
Load command 2
      cmd LC_SEGMENT_64
  cmdsize 72
  segname __LINKEDIT
   vmaddr 0x00000000006a0000
   vmsize 0x00000000007aa000
  fileoff 6840320
 filesize 8033764
  maxprot 0x00000007
 initprot 0x00000001
   nsects 0
    flags 0x0
Load command 3
          cmd LC_ID_DYLIB
      cmdsize 64
         name /opt/DD4hep/install/libDDCore.1.8.dylib (offset 24)
   time stamp 1 Thu Jan  1 01:00:01 1970
      current version 1.8.0
compatibility version 1.8.0
Load command 4
            cmd LC_DYLD_INFO_ONLY
        cmdsize 48
     rebase_off 6840320
    rebase_size 2896
       bind_off 6843216
      bind_size 14472
  weak_bind_off 6857688
 weak_bind_size 822136
  lazy_bind_off 7679824
 lazy_bind_size 28608
     export_off 7708432
    export_size 680768
Load command 5
     cmd LC_SYMTAB
 cmdsize 24
  symoff 8414272
   nsyms 112407
  stroff 10251924
 strsize 4622160
Load command 6
            cmd LC_DYSYMTAB
        cmdsize 80
      ilocalsym 0
      nlocalsym 96677
     iextdefsym 96677
     nextdefsym 15013
      iundefsym 111690
      nundefsym 717
         tocoff 0
           ntoc 0
      modtaboff 0
        nmodtab 0
   extrefsymoff 0
    nextrefsyms 0
 indirectsymoff 10212784
  nindirectsyms 9785
      extreloff 0
        nextrel 0
      locreloff 0
        nlocrel 0
Load command 7
     cmd LC_UUID
 cmdsize 24
    uuid 4507D143-9A8C-3116-91AF-F8DFEC2D20B6
Load command 8
      cmd LC_VERSION_MIN_MACOSX
  cmdsize 16
  version 10.13
      sdk 10.13
Load command 9
      cmd LC_SOURCE_VERSION
  cmdsize 16
  version 0.0
Load command 10
          cmd LC_LOAD_DYLIB
      cmdsize 48
         name @rpath/libCore.so (offset 24)
   time stamp 2 Thu Jan  1 01:00:02 1970
      current version 0.0.0
compatibility version 0.0.0
Load command 11
          cmd LC_LOAD_DYLIB
      cmdsize 48
         name @rpath/libImt.so (offset 24)
   time stamp 2 Thu Jan  1 01:00:02 1970
      current version 0.0.0
compatibility version 0.0.0
Load command 12
          cmd LC_LOAD_DYLIB
      cmdsize 48
         name @rpath/libRIO.so (offset 24)
   time stamp 2 Thu Jan  1 01:00:02 1970
      current version 0.0.0
compatibility version 0.0.0
Load command 13
          cmd LC_LOAD_DYLIB
      cmdsize 48
         name @rpath/libNet.so (offset 24)
   time stamp 2 Thu Jan  1 01:00:02 1970
      current version 0.0.0
compatibility version 0.0.0
Load command 14
          cmd LC_LOAD_DYLIB
      cmdsize 48
         name @rpath/libHist.so (offset 24)
   time stamp 2 Thu Jan  1 01:00:02 1970
      current version 0.0.0
compatibility version 0.0.0
Load command 15
          cmd LC_LOAD_DYLIB
      cmdsize 48
         name @rpath/libGraf.so (offset 24)
   time stamp 2 Thu Jan  1 01:00:02 1970
      current version 0.0.0
compatibility version 0.0.0
Load command 16
          cmd LC_LOAD_DYLIB
      cmdsize 48
         name @rpath/libGraf3d.so (offset 24)
   time stamp 2 Thu Jan  1 01:00:02 1970
      current version 0.0.0
compatibility version 0.0.0
Load command 17
          cmd LC_LOAD_DYLIB
      cmdsize 48
         name @rpath/libGpad.so (offset 24)
   time stamp 2 Thu Jan  1 01:00:02 1970
      current version 0.0.0
compatibility version 0.0.0
Load command 18
          cmd LC_LOAD_DYLIB
      cmdsize 48
         name @rpath/libTree.so (offset 24)
   time stamp 2 Thu Jan  1 01:00:02 1970
      current version 0.0.0
compatibility version 0.0.0
Load command 19
          cmd LC_LOAD_DYLIB
      cmdsize 48
         name @rpath/libTreePlayer.so (offset 24)
   time stamp 2 Thu Jan  1 01:00:02 1970
      current version 0.0.0
compatibility version 0.0.0
Load command 20
          cmd LC_LOAD_DYLIB
      cmdsize 48
         name @rpath/libRint.so (offset 24)
   time stamp 2 Thu Jan  1 01:00:02 1970
      current version 0.0.0
compatibility version 0.0.0
Load command 21
          cmd LC_LOAD_DYLIB
      cmdsize 48
         name @rpath/libPostscript.so (offset 24)
   time stamp 2 Thu Jan  1 01:00:02 1970
      current version 0.0.0
compatibility version 0.0.0
Load command 22
          cmd LC_LOAD_DYLIB
      cmdsize 48
         name @rpath/libMatrix.so (offset 24)
   time stamp 2 Thu Jan  1 01:00:02 1970
      current version 0.0.0
compatibility version 0.0.0
Load command 23
          cmd LC_LOAD_DYLIB
      cmdsize 48
         name @rpath/libPhysics.so (offset 24)
   time stamp 2 Thu Jan  1 01:00:02 1970
      current version 0.0.0
compatibility version 0.0.0
Load command 24
          cmd LC_LOAD_DYLIB
      cmdsize 48
         name @rpath/libMathCore.so (offset 24)
   time stamp 2 Thu Jan  1 01:00:02 1970
      current version 0.0.0
compatibility version 0.0.0
Load command 25
          cmd LC_LOAD_DYLIB
      cmdsize 48
         name @rpath/libThread.so (offset 24)
   time stamp 2 Thu Jan  1 01:00:02 1970
      current version 0.0.0
compatibility version 0.0.0
Load command 26
          cmd LC_LOAD_DYLIB
      cmdsize 48
         name @rpath/libMultiProc.so (offset 24)
   time stamp 2 Thu Jan  1 01:00:02 1970
      current version 0.0.0
compatibility version 0.0.0
Load command 27
          cmd LC_LOAD_DYLIB
      cmdsize 48
         name @rpath/libGeom.so (offset 24)
   time stamp 2 Thu Jan  1 01:00:02 1970
      current version 0.0.0
compatibility version 0.0.0
Load command 28
          cmd LC_LOAD_DYLIB
      cmdsize 48
         name @rpath/libGenVector.so (offset 24)
   time stamp 2 Thu Jan  1 01:00:02 1970
      current version 0.0.0
compatibility version 0.0.0
Load command 29
          cmd LC_LOAD_DYLIB
      cmdsize 72
         name /opt/xerces/install/lib/libxerces-c-3.2.dylib (offset 24)
   time stamp 2 Thu Jan  1 01:00:02 1970
      current version 0.0.0
compatibility version 0.0.0
Load command 30
          cmd LC_LOAD_DYLIB
      cmdsize 72
         name /opt/DD4hep/install/libDDParsers.1.8.dylib (offset 24)
   time stamp 2 Thu Jan  1 01:00:02 1970
      current version 1.8.0
compatibility version 1.8.0
Load command 31
          cmd LC_LOAD_DYLIB
      cmdsize 80
         name /opt/DD4hep/install/libDD4hepGaudiPluginMgr.1.8.dylib (offset 24)
   time stamp 2 Thu Jan  1 01:00:02 1970
      current version 1.8.0
compatibility version 1.8.0
Load command 32
          cmd LC_LOAD_DYLIB
      cmdsize 48
         name /usr/lib/libc++.1.dylib (offset 24)
   time stamp 2 Thu Jan  1 01:00:02 1970
      current version 400.9.0
compatibility version 1.0.0
Load command 33
          cmd LC_LOAD_DYLIB
      cmdsize 56
         name /usr/lib/libSystem.B.dylib (offset 24)
   time stamp 2 Thu Jan  1 01:00:02 1970
      current version 1252.50.4
compatibility version 1.0.0
Load command 34
      cmd LC_FUNCTION_STARTS
  cmdsize 16
  dataoff 8389200
 datasize 24952
Load command 35
      cmd LC_DATA_IN_CODE
  cmdsize 16
  dataoff 8414152
 datasize 120
Load command 36
          cmd LC_RPATH
      cmdsize 40
         path /opt/DD4hep/install/lib (offset 12)
Load command 37
          cmd LC_RPATH
      cmdsize 40
         path /opt/root/root-install/lib (offset 12)

**Comment by andresailer** [comment]
Please continue here #425

**Pull request merged**
